# -*- coding: utf-8 -*-
"""01_Data_Cleaning

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-UfwtIYPnLb-vf0kMoO0Zn3Hfj7nYkzz
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#Load dataset
df = pd.read_csv('/content/games_dataset.csv')

df.head(5)

df.info()

df.shape

df.isnull().sum()

#Handle Missing Values
#For Numeric Values
#df['Release Year'] = df['Release Year'].fillna(df['Release Year'].median())
#df['User Rating'] = df['User Rating'].fillna(df['User Rating'].median())

#for Categorical Values
#df['Genre'] = df['Genre'].fillna("Unknown")
#df['Platform'] = df['Platform'].fillna("Unknown")

df.duplicated().sum()

#Remove Duplicated Values
#df.drop_duplicates(inplace=True)

#Handle Anomalous Values
#Replace invalid release year with NaN
df.loc[
    (df['Release Year']<1980)|
    (df['Release Year']>2025),
    "Release Year"
] = np.nan

df['Release Year'].min()
df['Release Year'].max()

#Replace invalid Ratings with Nan
df.loc[
    (df['User Rating']<0)|
    (df['User Rating']>10),
    "User Rating"
] = np.nan

df['Genre'].unique()

#Fill newly created missing values
df['Release Year'] = df['Release Year'].fillna(df['Release Year'].median())
df['User Rating'] = df['User Rating'].fillna(df['User Rating'].median())

#Standardize Genre
df['Genre'] = (
    df['Genre']
    .astype(str)
    .str.strip()
    .str.title()
)

#Handle Special Formatting
df['Genre'] = df['Genre'].replace({
    "Role Playing":"Role-playing",
    "Role-Playing":"Role-playing"
})

df['Platform'].unique()

#Standardize Platform
df['Platform'] = (
    df['Platform']
    .astype(str)
    .str.strip()
  )

#Handle Special Formatting
df['Platform'] =df['Platform'].replace({
    "playstation": "PlayStation",
    "PLAYSTATION": "PlayStation",
    "pc":"PC",
    "PC":"PC",
    "xbox":"Xbox",
    "mobile":"Mobile",
    "nintendo switch":"Nintendo Switch"
})

df['Platform']

#Create Decade Feature
df['Decade'] = (
    (df['Release Year']//10)*10
).astype(int).astype(str) + "s"

