# -*- coding: utf-8 -*-
"""02_eda_analysis 

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wJF0zWf4t1ML1GCHQCXydX2DXC394UkX
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#Load dataset
df = pd.read_csv('/content/games_dataset.csv')

#Analyze trends by Genre
genre_rating = (
    df.groupby('Genre')['User Rating']
    .mean()
    .sort_values(ascending=False)
)
print(genre_rating)

#Visualize Genre Ratings
genre_rating.sort_values().plot(
    kind='barh',
    figsize=(12,8)
)
plt.title("Average User Rating by Genre")
plt.xlabel("Average User Rating")
plt.ylabel("Genre")
plt.show()

#Analyze trends by Platform
platform_rating = (
    df.groupby('Platform')['User Rating']
    .mean()
    .sort_values(ascending=False)
)
print(platform_rating)

platform_rating.sort_values().plot(
    kind='bar',
    figsize=(12,8)
)
plt.title("Average User Rating by Platform")
plt.xlabel("Platform")
plt.ylabel("Average User Rating")
plt.xticks(rotation=0)
plt.show()

#Analyze trend by Release Year
year_rating = (
    df.groupby('Release Year')['User Rating']
    .mean()
)
print(year_rating)

year_rating.plot(
    kind='line',
    figsize=(12,8),
    marker='o'
)
plt.title("Average User Rating by Release Year")
plt.xlabel("Release Year")
plt.ylabel("Average User Rating")
plt.grid(True)
plt.show()

#Distribution of User Ratings by Genre
plt.figure(figsize=(12,8))
df.boxplot(
    column="User Rating",
    by="Genre",
    rot=45
)
plt.title("Distribution of User Rating by Genre")
plt.suptitle("")
plt.xlabel("Genre")
plt.ylabel("User Rating")
plt.show()

#Distribution of User Ratings by Platform
plt.figure(figsize=(12,8))
df.boxplot(
    column="User Rating",
    by="Platform"
)
plt.title("Distribution of User Rating by Platform")
plt.suptitle("")
plt.xlabel("Platform")
plt.ylabel("User Rating")
plt.show()

#Top 5 Genres by Average User Rating
top5_genres = (
    df.groupby('Genre')['User Rating']
    .mean()
    .sort_values(ascending=False)
    .head(5)
)
print(top5_genres)

#Visualize
top5_genres.sort_values().plot(
    kind='barh',
    figsize=(12,8)
)
plt.title("Top 5 Genres by Average User Rating")
plt.xlabel("Average User Rating")
plt.ylabel("Genre")
plt.show()

#Top 5 Platforms by Average User Rating
top5_platforms = (
    df.groupby('Platform')['User Rating']
    .mean()
    .sort_values(ascending=False)
    .head(5)
)
print(top5_platforms)

#Visualize
top5_platforms.sort_values().plot(
    kind='bar',
    figsize=(12,8)
)
plt.title("Top 5 Platforms by Average User Rating")
plt.xlabel("Average User Rating")
plt.ylabel("Platform")
plt.show()
