# -*- coding: utf-8 -*-
"""03_statistical_analysis 

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZXi0DbvrabTnziEY29HVqaEab0nBLyeK
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#Load dataset
df = pd.read_csv('/content/games_dataset.csv')

#Time Series Analysis - Release & Rating by Decade
df['Decade'].unique()

decade_analysis = (
    df.groupby('Decade')
    .agg(
        Game_Release = ('Game Name', 'count'),
        Average_Rating=('User Rating','mean')
    )
    .reset_index()
)
print(decade_analysis)

#Visualize number of release
plt.figure(figsize=(12,8))
plt.bar(
    decade_analysis['Decade'].astype(str),
    decade_analysis['Game_Release']
)
plt.title("Number of Game Release by Decade")
plt.xlabel("Decade")
plt.ylabel("Number of Game Release")
plt.show()

#Visualize average Ratings
plt.figure(figsize=(12,8))
plt.plot(
    decade_analysis['Decade'].astype(str),
    decade_analysis['Average_Rating'],
    marker='o'
)
plt.title("Average User Rating by Decade")
plt.xlabel("Decade")
plt.ylabel("Average User Rating")
plt.grid(True)
plt.show()

#Hypothesis Test
#more then two platforms : so use one-way anova test
#Check Average Ratings
platform_summary = (
    df.groupby('Platform')['User Rating']
    .agg(['count','mean','std'])
    .sort_values('mean',ascending=False)
)

print(platform_summary)

#Perform One-Way ANOVA
from scipy import stats

platform_groups = [
    group['User Rating'].dropna()
    for platform, group in df.groupby('Platform')
]

f_statistic, p_value = stats.f_oneway(*platform_groups)

print("F-statistic:", f_statistic)
print("P-value:", p_value)

alpha = 0.05

if p_value < alpha:
    print("Reject the null hypothesis. There is a significant difference in average user ratings between at least two platforms.")
else:
    print("Fail to reject the null hypothesis. There is no significant difference in average user ratings between the platforms.")

#Correlation Analysis
correlation = df['Release Year'].corr(
    df['User Rating'],
    method='pearson'
)
print("Correlation:",correlation)

#Visualize the Correlation
plt.figure(figsize=(10,6))

plt.scatter(
    df['Release Year'],
    df['User Rating'],
    alpha=0.5
)

plt.title("Release Year vs User Rating")
plt.xlabel("Release Year")
plt.ylabel("User Rating")
plt.show()

#Calculate Correlation Matrix
correlation_matrix = df[
    ['Release Year', 'User Rating']
].corr()

print(correlation_matrix)

#Features
x = df[['Genre','Platform','Release Year']]

y = df['User Rating']

print(x.head())
print(y.head())
